services:
  # 1. Go REST API Gateway & Embedded Worker Engine
  - type: web
    name: email-dispatcher-api
    env: docker
    dockerfilePath: ./infra/Dockerfile.api
    plan: free
    region: oregon
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: email-dispatcher-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: email-dispatcher-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: email-dispatcher-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: email-dispatcher-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: email-dispatcher-db
          property: database
      - key: REDIS_HOST
        fromService:
          type: redis
          name: email-dispatcher-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: email-dispatcher-redis
          property: port

  # 2. Redis Key-Value Store
  - type: redis
    name: email-dispatcher-redis
    plan: free
    region: oregon
    ipAllowList: []

databases:
  # 3. PostgreSQL Database
  - name: email-dispatcher-db
    databaseName: email_dispatcher
    plan: free
    region: oregon



